name: environmental-filtering
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Runtime
  - r-base>=4.2.0
  - r-optparse
  - r-stringr
  - r-data.table
  - r-vegan
  - r-ape
  - r-plyr
  - r-reshape2
  - bioconductor-phyloseq
  - r-picante
  - r-arrow

  # Required to install R NST package from GitHub
  - cmake

  # Pipeline orchestration
  - nextflow>=23.04
